apiVersion: apps/v1
kind: Deployment
metadata:
  name: udemy-spring-security
  namespace: default
  labels:
    app: udemy-spring-security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udemy-spring-security
  template:
    metadata:
      labels:
        app: udemy-spring-security
    spec:
      containers:
        - name: udemy-spring-security
          image: 192.168.1.100:5000/udemy.spring.security:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"