apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-sample
  namespace: default
  labels:
    app: spring-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-sample
  template:
    metadata:
      labels:
        app: spring-sample
    spec:
      containers:
        - name: spring-sample
          image: registry.localhost:5000/spring-sample:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"