apiVersion: v1
kind: Service
metadata:
  name: udemy.spring.security
  namespace: default
spec:
  selector:
    app: udemy.spring.security
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort