apiVersion: v1
kind: Service
metadata:
  name: spring-sample
  namespace: default
spec:
  selector:
    app: spring-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort