name: Delete merged feature branches

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Delete feature branch
        run: |
          git push origin --delete "${GITHUB_HEAD_REF}"